### ISSUE TITLE
jupyter_micropython_kernel.pyboard.PyboardError: timeout waiting for first EOF reception

### ISSUE THREAD

**Issue by chrisb2** [adafruit/jupyter_micropython_kernel#1]
**Environment (Anaconda on Windows 10):**

(micropython) c:\aProject\jupyter_micropython_kernel>python -V
Python 3.6.0 :: Anaconda 4.3.0 (64-bit)
MicroPython v1.8.7-65-g7d08bc2 on 2017-01-23; PYBv1.1 with STM32F405RG

**Running:**
```
led = pyb.LED(2)
while True:
    led.toggle()
    pyb.delay(1000)
```

The LED flashes about 5 times, then the above error occurs on the console where I started the notebook. The stack trace is below. I tried increasing the timeout from 10 to 20 at line 247 of pyboard.py, this resulted in about 10 flashes before the error occurred. Decreasing the delay in the above code to 500ms resulted in about 20 flashes.

```
ERROR:tornado.general:Uncaught exception, closing connection.
Traceback (most recent call last):
  File "C:\tools\Anaconda3\lib\site-packages\zmq\eventloop\zmqstream.py", line 414, in _run_callback
    callback(*args, **kwargs)
  File "C:\tools\Anaconda3\lib\site-packages\tornado\stack_context.py", line 275, in null_wrapper
    return fn(*args, **kwargs)
  File "C:\tools\Anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 276, in dispatcher
    return self.dispatch_shell(stream, msg)
  File "C:\tools\Anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 228, in dispatch_shell
    handler(stream, idents, msg)
  File "C:\tools\Anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 390, in execute_request
    user_expressions, allow_stdin)
  File "c:\aProject\jupyter_micropython_kernel\jupyter_micropython_kernel\kernel.py", line 47, in do_execute
    result, error = self._board.exec_raw(code)
  File "c:\aProject\jupyter_micropython_kernel\jupyter_micropython_kernel\pyboard.py", line 249, in exec_raw
    return self.follow(timeout, data_consumer)
  File "c:\aProject\jupyter_micropython_kernel\jupyter_micropython_kernel\pyboard.py", line 213, in follow
    raise PyboardError('timeout waiting for first EOF reception')
jupyter_micropython_kernel.pyboard.PyboardError: timeout waiting for first EOF reception
ERROR:tornado.general:Uncaught exception, closing connection.
Traceback (most recent call last):
  File "C:\tools\Anaconda3\lib\site-packages\zmq\eventloop\zmqstream.py", line 414, in _run_callback
    callback(*args, **kwargs)
  File "C:\tools\Anaconda3\lib\site-packages\tornado\stack_context.py", line 275, in null_wrapper
    return fn(*args, **kwargs)
  File "C:\tools\Anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 276, in dispatcher
    return self.dispatch_shell(stream, msg)
  File "C:\tools\Anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 228, in dispatch_shell
    handler(stream, idents, msg)
  File "C:\tools\Anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 390, in execute_request
    user_expressions, allow_stdin)
  File "c:\aProject\jupyter_micropython_kernel\jupyter_micropython_kernel\kernel.py", line 47, in do_execute
    result, error = self._board.exec_raw(code)
  File "c:\aProject\jupyter_micropython_kernel\jupyter_micropython_kernel\pyboard.py", line 249, in exec_raw
    return self.follow(timeout, data_consumer)
  File "c:\aProject\jupyter_micropython_kernel\jupyter_micropython_kernel\pyboard.py", line 213, in follow
    raise PyboardError('timeout waiting for first EOF reception')
jupyter_micropython_kernel.pyboard.PyboardError: timeout waiting for first EOF reception
ERROR:tornado.general:Uncaught exception, closing connection.
Traceback (most recent call last):
  File "C:\tools\Anaconda3\lib\site-packages\zmq\eventloop\zmqstream.py", line 440, in _handle_events
    self._handle_recv()
  File "C:\tools\Anaconda3\lib\site-packages\zmq\eventloop\zmqstream.py", line 472, in _handle_recv
    self._run_callback(callback, msg)
  File "C:\tools\Anaconda3\lib\site-packages\zmq\eventloop\zmqstream.py", line 414, in _run_callback
    callback(*args, **kwargs)
  File "C:\tools\Anaconda3\lib\site-packages\tornado\stack_context.py", line 275, in null_wrapper
    return fn(*args, **kwargs)
  File "C:\tools\Anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 276, in dispatcher
    return self.dispatch_shell(stream, msg)
  File "C:\tools\Anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 228, in dispatch_shell
    handler(stream, idents, msg)
  File "C:\tools\Anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 390, in execute_request
    user_expressions, allow_stdin)
  File "c:\aProject\jupyter_micropython_kernel\jupyter_micropython_kernel\kernel.py", line 47, in do_execute
    result, error = self._board.exec_raw(code)
  File "c:\aProject\jupyter_micropython_kernel\jupyter_micropython_kernel\pyboard.py", line 249, in exec_raw
    return self.follow(timeout, data_consumer)
  File "c:\aProject\jupyter_micropython_kernel\jupyter_micropython_kernel\pyboard.py", line 213, in follow
    raise PyboardError('timeout waiting for first EOF reception')
jupyter_micropython_kernel.pyboard.PyboardError: timeout waiting for first EOF reception
ERROR:tornado.general:Uncaught exception, closing connection.
Traceback (most recent call last):
  File "C:\tools\Anaconda3\lib\site-packages\zmq\eventloop\zmqstream.py", line 440, in _handle_events
    self._handle_recv()
  File "C:\tools\Anaconda3\lib\site-packages\zmq\eventloop\zmqstream.py", line 472, in _handle_recv
    self._run_callback(callback, msg)
  File "C:\tools\Anaconda3\lib\site-packages\zmq\eventloop\zmqstream.py", line 414, in _run_callback
    callback(*args, **kwargs)
  File "C:\tools\Anaconda3\lib\site-packages\tornado\stack_context.py", line 275, in null_wrapper
    return fn(*args, **kwargs)
  File "C:\tools\Anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 276, in dispatcher
    return self.dispatch_shell(stream, msg)
  File "C:\tools\Anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 228, in dispatch_shell
    handler(stream, idents, msg)
  File "C:\tools\Anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 390, in execute_request
    user_expressions, allow_stdin)
  File "c:\aProject\jupyter_micropython_kernel\jupyter_micropython_kernel\kernel.py", line 47, in do_execute
    result, error = self._board.exec_raw(code)
  File "c:\aProject\jupyter_micropython_kernel\jupyter_micropython_kernel\pyboard.py", line 249, in exec_raw
    return self.follow(timeout, data_consumer)
  File "c:\aProject\jupyter_micropython_kernel\jupyter_micropython_kernel\pyboard.py", line 213, in follow
    raise PyboardError('timeout waiting for first EOF reception')
jupyter_micropython_kernel.pyboard.PyboardError: timeout waiting for first EOF reception
Traceback (most recent call last):
  File "C:\tools\Anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\tools\Anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "c:\aProject\jupyter_micropython_kernel\jupyter_micropython_kernel\__main__.py", line 22, in <module>
    IPKernelApp.launch_instance(kernel_class=make_micropython_kernel(port, baud))
  File "C:\tools\Anaconda3\lib\site-packages\traitlets\config\application.py", line 658, in launch_instance
    app.start()
  File "C:\tools\Anaconda3\lib\site-packages\ipykernel\kernelapp.py", line 474, in start
    ioloop.IOLoop.instance().start()
  File "C:\tools\Anaconda3\lib\site-packages\zmq\eventloop\ioloop.py", line 177, in start
    super(ZMQIOLoop, self).start()
  File "C:\tools\Anaconda3\lib\site-packages\tornado\ioloop.py", line 887, in start
    handler_func(fd_obj, events)
  File "C:\tools\Anaconda3\lib\site-packages\tornado\stack_context.py", line 275, in null_wrapper
    return fn(*args, **kwargs)
  File "C:\tools\Anaconda3\lib\site-packages\zmq\eventloop\zmqstream.py", line 440, in _handle_events
    self._handle_recv()
  File "C:\tools\Anaconda3\lib\site-packages\zmq\eventloop\zmqstream.py", line 472, in _handle_recv
    self._run_callback(callback, msg)
  File "C:\tools\Anaconda3\lib\site-packages\zmq\eventloop\zmqstream.py", line 414, in _run_callback
    callback(*args, **kwargs)
  File "C:\tools\Anaconda3\lib\site-packages\tornado\stack_context.py", line 275, in null_wrapper
    return fn(*args, **kwargs)
  File "C:\tools\Anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 276, in dispatcher
    return self.dispatch_shell(stream, msg)
  File "C:\tools\Anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 228, in dispatch_shell
    handler(stream, idents, msg)
  File "C:\tools\Anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 390, in execute_request
    user_expressions, allow_stdin)
  File "c:\aProject\jupyter_micropython_kernel\jupyter_micropython_kernel\kernel.py", line 47, in do_execute
    result, error = self._board.exec_raw(code)
  File "c:\aProject\jupyter_micropython_kernel\jupyter_micropython_kernel\pyboard.py", line 249, in exec_raw
    return self.follow(timeout, data_consumer)
  File "c:\aProject\jupyter_micropython_kernel\jupyter_micropython_kernel\pyboard.py", line 213, in follow
    raise PyboardError('timeout waiting for first EOF reception')
jupyter_micropython_kernel.pyboard.PyboardError: timeout waiting for first EOF reception
[I 19:37:53.059 NotebookApp] KernelRestarter: restarting kernel (1/5)
WARNING:root:kernel 42b2a430-b002-4b0b-a5b3-389c71ac699a restarted
```

**Comment by chrisb2** [comment]
Sorry, I just realized from listening the video again that this is the timeout due to infinite loops you mention, so I am closing this issue.
