### ISSUE TITLE
No longer working with CircuitPython 2.2.3

### ISSUE THREAD

**Issue by robmarkcole** [adafruit/jupyter_micropython_kernel#11]
Updated my trinket M0 to CircuitPython 2.2.3 and the jupyter integration is no longer working. In my logs I get:

```
[I 20:19:36.190 NotebookApp] Saving file at /Documents/Github/Useful-python/Mircropython/Micropython with Adafruit M0 7-2-2018.ipynb
DEBUG:jupyter_micropython_kernel.kernel:Opening MicroPython board connection on port: /dev/cu.usbmodem14341 baud: 115200
Traceback (most recent call last):
  File "/anaconda3/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/anaconda3/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/anaconda3/lib/python3.6/site-packages/jupyter_micropython_kernel-0.1.0-py3.6.egg/jupyter_micropython_kernel/__main__.py", line 22, in <module>
    IPKernelApp.launch_instance(kernel_class=make_micropython_kernel(port, baud))
  File "/anaconda3/lib/python3.6/site-packages/traitlets/config/application.py", line 657, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-123>", line 2, in initialize
  File "/anaconda3/lib/python3.6/site-packages/traitlets/config/application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "/anaconda3/lib/python3.6/site-packages/ipykernel/kernelapp.py", line 457, in initialize
    self.init_kernel()
  File "/anaconda3/lib/python3.6/site-packages/ipykernel/kernelapp.py", line 368, in init_kernel
    user_ns=self.user_ns,
  File "/anaconda3/lib/python3.6/site-packages/traitlets/config/configurable.py", line 412, in instance
    inst = cls(*args, **kwargs)
  File "/anaconda3/lib/python3.6/site-packages/jupyter_micropython_kernel-0.1.0-py3.6.egg/jupyter_micropython_kernel/kernel.py", line 42, in __init__
    self._board.enter_raw_repl()
  File "/anaconda3/lib/python3.6/site-packages/jupyter_micropython_kernel-0.1.0-py3.6.egg/jupyter_micropython_kernel/pyboard.py", line 204, in enter_raw_repl
    raise PyboardError('could not enter raw repl')
```

**Comment by ladyada** [comment]
@robmarkcole hiya do you know when the last version it worked?
@tdicola on tidyday, please check this issue, and fix so circuitpython is functional again

**Comment by robmarkcole** [comment]
Hi it worked with whatever firmware the Trinket M0 shipped with (did't ever check version) - I updated the firmware for the first time yesterday

**Comment by tdicola** [comment]
I can't repro the issue, it seems to connect fine to a Trinket M0 with 2.2.3.  Here's one out of the box with 2.0:
<img width="666" alt="screen shot 2018-02-19 at 2 06 34 pm" src="https://user-images.githubusercontent.com/1332183/36398970-8f72c880-157e-11e8-88c9-187829bf946c.png">
And the same upgrade to 2.2.3:
<img width="627" alt="screen shot 2018-02-19 at 2 09 13 pm" src="https://user-images.githubusercontent.com/1332183/36398975-9832be80-157e-11e8-8282-303d1a61556e.png">

You might try a different USB cable to make sure you're getting a good connection to the board.  Also try manually resetting the board and make sure there isn't a pre-existing main.py that might be running and spamming unexpected output.
